backend/blog/urls.py
from django.urls import path
from .views import HomeView, AboutView, ContactView, profile, BlogDetail, SettingView, profilupdate, Account_Deleted, AddPostView


urlpatterns = [
    path("about/", AboutView.as_view(), name="about"),
    path("contact/", ContactView.as_view(), name="contact"),
    path("add-post/", AddPostView.as_view(), name="add-post"),
    path("user/<str:username>/", profile, name='profile'),
    path("user/<str:username>/update/", profilupdate, name='profile_update'),
    path('user/<str:username>/account-deleted/', Account_Deleted, name="delete-account"),
    path("<str:slug>/", BlogDetail.as_view(), name="blog_detail"),
]

backend/project/urls.py
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.conf import settings
from blog.views import HomeView, SettingView


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomeView.as_view(), name="home"),
    path("setting/", SettingView.as_view(),name='setting'),
    path('', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('auth/', include('authentication.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/blog/models.py
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.db import models

CATEGORY_CHOICES = [
    ('health','Health'),
    ('tech','Technology'),
    ('food','Food'),
    ('travel','Travel'),
    ('music','Music'),
    ('lifestyle','Lifestyle')
]

class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=250)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='images/')
    category = models.CharField(max_length=9, choices=CATEGORY_CHOICES,blank = True, null =True)
    body = RichTextField()
    views_count = models.IntegerField(default=0)
    slug = models.SlugField(blank = True, null =True)
    Timestamp = models.DateTimeField(auto_now_add=True)
    Updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title[:50])
        super(Blog, self).save(*args, **kwargs) # Call the real save() method

    def increase(self):
        self.views_count += 1
        self.save()


class Contact(models.Model):
    first_name = models.CharField(max_length = 80)
    last_name = models.CharField(max_length = 80)
    email = models.EmailField(max_length=254)
    message = RichTextField(max_length=1000)
    add_date = models.DateTimeField(auto_now_add=True, null=True, blank=True)
    update_date = models.DateTimeField(auto_now=True, null=True, blank=True)


    def __str__(self):
        return str(self.fname)

backend/templates/about.html
{% extends 'theme/base.html' %} {% load static %} {% block title %}
<title> {{ block.super }} | About Us</title>
{% endblock title %} 
{% block body %}
<div class="bg-light">
  <div class="container py-5">
    <div class="row h-100 align-items-center py-5">
      <div class="col-lg-6">
        <h1 class="display-4">About us page</h1>
        <p class="lead text-muted mb-0">We Support to get free book to Human.</p>
        <p class="lead text-muted">Our Website <a href="{% url 'home' %}" class="text-muted"> 
                    <u>Coding Addict</u></a>
        </p>
      </div>
      <div class="col-lg-6 d-none d-lg-block"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/illus_kftyh4.png" alt="" class="img-fluid"></div>
    </div>
  </div>
</div>

<div class="bg-white py-5">
  <div class="container py-5">
    <div class="row align-items-center mb-5">
      <div class="col-lg-6 order-2 order-lg-1"><i class="fa fa-bar-chart fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">Blog Update Time</h2>
        <p class="font-italic text-muted mb-4">User Can Upload or Content to website.</p><a href="https://www.researchgate.net/post/which_Algorithm_is_best_for_book_recommendation_system" class="btn btn-light px-5 rounded-pill shadow-sm">Learn More</a>
      </div>
      <div class="col-lg-5 px-5 mx-auto order-1 order-lg-2"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556834139/img-1_e25nvh.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
    </div>
    <div class="row align-items-center">
      <div class="col-lg-5 px-5 mx-auto"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556834136/img-2_vdgqgn.jpg" alt="" class="img-fluid mb-4 mb-lg-0"></div>
      <div class="col-lg-6"><i class="fa fa-leaf fa-2x mb-3 text-primary"></i>
        <h2 class="font-weight-light">Blog according to user interest</h2>
        <p class="font-italic text-muted mb-4">We Use Best algorithm to suggest Blog to user.</p><a href="https://www.researchgate.net/post/which_Algorithm_is_best_for_book_recommendation_system" class="btn btn-light px-5 rounded-pill shadow-sm">Learn More</a>
      </div>
    </div>
  </div>
</div>

<div class="bg-light py-5">
  <div class="container py-5">
    <div class="row mb-4">
      <div class="col-lg-5">
        <h2 class="display-4 font-weight-light">Our team</h2>
        <p class="font-italic text-muted">People work with us.</p>
      </div>
    </div>

    <div class="row text-center">
      <!-- Team item-->
      <div class="col-xl-3 col-sm-6 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="{% static 'image/Ravi.jpg' %}" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Ravi Choudhary</h5>
          <span class="small text-uppercase text-muted">CEO - Founder</span></br>
          <span class="small text-uppercase text-muted">username - <a href="{%url 'home' %}ravichoudhary18">ravichoudhary18</a></span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="https://www.facebook.com/ravi18choudhary18" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="https://www.twitter.com/rc181219" class="social-link"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="https://www.instagram.com/ravichoudhary18" class="social-link"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="https://www.linkedin.com/in/ravi-choudhary-088a06104" class="social-link"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <!-- End-->

      <!-- Team item-->
      <div class="col-xl-3 col-sm-6 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556834130/avatar-3_hzlize.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Rohit Yado</h5><span class="small text-uppercase text-muted">Editer</span> </br>
          <span class="small text-uppercase text-muted">username - <a href='{%url 'home' %}rohit18'>rohit18</a></span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <!-- End-->

      <!-- Team item-->
      <div class="col-xl-3 col-sm-6 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556834133/avatar-2_f8dowd.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">Tom Sunderland</h5><span class="small text-uppercase text-muted">Manger</span></br>
          <span class="small text-uppercase text-muted">username - <a href='{%url 'home' %}Sunderland18'>Sunderland18</a></span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <!-- End-->

      <!-- Team item-->
      <div class="col-xl-3 col-sm-6 mb-5">
        <div class="bg-white rounded shadow-sm py-5 px-4"><img src="https://res.cloudinary.com/mhmd/image/upload/v1556834133/avatar-1_s02nlg.png" alt="" width="100" class="img-fluid rounded-circle mb-3 img-thumbnail shadow-sm">
          <h5 class="mb-0">John Tarly</h5><span class="small text-uppercase text-muted">Tech</span></br>
          <span class="small text-uppercase text-muted">username - <a href='{%url 'home' %}John18'></a>John18</span>
          <ul class="social mb-0 list-inline mt-3">
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-facebook-f"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-twitter"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-instagram"></i></a></li>
            <li class="list-inline-item"><a href="#" class="social-link"><i class="fa fa-linkedin"></i></a></li>
          </ul>
        </div>
      </div>
      <!-- End-->

    </div>
  </div>
</div>

{% endblock body %}

backend/templates/add-post.html
{% extends "theme/base.html" %}
{% load static %}
{% block title %}
  <title>
      {{ block.super }} | Add Post
  </title>
  <script type="text/javascript" src='{% static "ckeditor/ckeditor-init.js" %}'></script>
<script type="text/javascript" src='{% static "ckeditor/ckeditor/ckeditor.js" %}''></script>
{% endblock title %}

{% block body %}
<div class="container mt-5 mb-5">
    <form>
        {% csrf_token %}
          <label for="{{form.title.label}}">{{form.title.label}}</label>
          {{form.title}}
          <small id="{{form.title.label}}" class="form-text">
          You can Add If You wnat Your style in Post.        
        </small><br><br>
        <label for="{{form.description.label}}">{{form.description.label}}</label><br>
        <small id="{{form.description.label}}" class="form-text">
        You can Add If You wnat Your style in Post.        
        </small><br>
          {{form.description}}
            <div class="form-group col-md-4">
                <label for="{{form.category.label}}">{{form.category.label}}</label><br>
                {{form.category}}
            </div><br>
            <div class="form-group">
              <label for="{{form.image.label}}">{{form.image.label}}</label><br>
                {{form.image}}
            </div><br>
            <div class="form-group col-md-4">
                <label for="{{form.body.label}}">{{form.body.label}}</label><br>
                {{form.body}}
            </div><br>
            <button type="submit" class="btn btn-primary">Post</button>
    </form>
</div>
{% endblock body %}
{% block javascript %}
  <script>
      $("#id_title").addClass('form-control')
      $("#id_description").addClass('form-control')
      $("textarea").css("height","92px")
      $("#id_image").addClass('form-control-file')
      $("#id_category").addClass('form-control')
      $("#id_body").css("height","1000px")
      $("#id_body").css("width","100%")
  </script>
{% endblock javascript %}

backend/templates/contact.html
{% extends 'theme/base.html' %} {% load static %} {% block title %}
<title> {{ block.super }} | Contact Us</title>
{% endblock title %} 
{% block style %}
<style>
    body {
        color: #566787;
        background: #f5f5f5;
        font-family: "Open Sans", sans-serif;
    }
    
    .contact-form {
        padding: 50px;
        margin: 30px 0;
    }
    
    .contact-form h1 {
        text-transform: uppercase;
        margin: 0 0 15px;
    }
    
    .contact-form .form-control,
    .contact-form .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    
    .contact-form .btn-primary {
        min-width: 150px;
        background: #299be4;
        border: none;
    }
    
    .contact-form .btn-primary:hover {
        background: #1c8cd7;
    }
    
    .contact-form label {
        opacity: 0.9;
    }
    
    .contact-form textarea {
        resize: vertical;
    }
    
    .hint-text {
        font-size: 15px;
        padding-bottom: 15px;
        opacity: 0.8;
    }
    
    .bs-example {
        margin: 20px;
    }
</style>

{% endblock style %} 
{% block body %}
<div class="container-xl">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="contact-form">
                <h1>Contact Us</h1>
                <p class="hint-text">We'd love to hear from you, please drop us a line if you've any query.</p>
                <form method="post">
                    {% csrf_token %}
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="inputFirstName">First Name</label> 
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <label for="inputLastName">Last Name</label> 
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail">Email Address</label> {{ form.email }}
                    </div>
                    <div class="form-group">
                        <label for="inputMessage">Message</label><br> 
                        {{ form.message }} <br>
                    </div>
                    <input type="submit" class="btn btn-primary" value="Submit">
                    <input type="reset" class="btn btn-primary" value="Reset">
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock body %} 
{% block javascript %}
<script>
    $(document).ready(function() {
        $('#id_first_name').addClass('form-control');
        $('#id_last_name').addClass('form-control');
        $('#id_email').addClass('form-control');
        $('#id_massage').addClass('form-control');
    });
</script>
{% endblock javascript %}

backend/templates/delete-account.html
{% extends 'theme/base.html' %} {% load static %} {% block title %}
<title> {{ block.super }} | Delete Account</title>
{% endblock title %} {% block body %}
<div class="mt-5 text-center" style="height: 78vh;">
    <div class="mt-5 text-center">
        <h3 class="font">
            <b>
                Do You want to Delete your Account ?
            </b>
        </h3><br>
        <form action="" method="POST">
            {% csrf_token %}
            <button class="btn btn-info font px-3">
                <b>Yes</b>
            </button>
            <a href="/" class="btn btn-warning font px-3">
                <b>No</b>
            </a>
        </form>
    </div>
</div>
{% endblock body %}

backend/templates/home.html
{% extends "theme/base.html" %} {% block title %}
<title>{{ block.super }} | Home</title>
{% endblock title %} {% block style %}
<style></style>
{% endblock style %} {% block body %}
<section class="menu">
  <div class="title">
    <h2>Our Category</h2>
    <div class="underline"></div>
  </div>
  <!-- filter Button -->
  <div class="btn-container">
    <!-- <button class="filter-btn" data-id="all">All</button>
      <button class="filter-btn" data-id="breakfast">Breakfast</button>
      <button class="filter-btn" data-id="lunch">Lunch</button>
      <button class="filter-btn" data-id="shakes">Shakes</button> -->
  </div>
  <!-- menu Item -->
  <div class="section-center">
    <!-- Single Item -->
    <!-- <article class="menu-item">
          <img src="menu-item.jpeg" class="photo" alt="menu item">
          <div class="item-info">
              <header>
                  <h4>ButterMilk Pancakes</h4>
                  <h4 class="price">$15</h4>
              </header>
              <p class="item-text">Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos saepe deserunt
                  consequatur perferendis voluptas asperiores facere aliquid nostrum fugit excepturi ipsum qui,
                  ipsam iste odio. Voluptatum odio quas ipsum delectus?
              </p>
          </div>
      </article> -->
    <!-- End of single Item -->
  </div>
</section>
{% endblock body %} {% block javascript %}
<script language="javascript">

  const menu = [
    {% for blog in object_list %}
      {
        id: {{ blog.id }},
        user: "{{blog.user}}",
        title: "{{blog.title | safe}}",
        description : "{{blog.description | safe}}",
        body: `{{blog.body |striptags | truncatewords:20}}`,
        img : "{{blog.image.url}}",
        category : "{{blog.category}}",
        slug : "{{blog.slug}}",
        views_count: {{ blog.views_count }},
      },
  {% endfor %}
  ];

    const sectionCenter = document.querySelector(".section-center");
    const container = document.querySelector(".btn-container")


    window.addEventListener("DOMContentLoaded", () => {
      displayMenuItem(menu);
      displayMenuButtion();
    });

    function displayMenuItem(menuItems) {
      let displayMenu = menuItems.map((item) => {
        // console.log(itme)
        return `
        <a href="/${item.slug}">
        <article class="menu-item">
            <img src=${item.img} class="photo" alt="${item.img}">
            <div class="item-info">
              <header>
                <h4>${item.title}</h4>
                <h4 class="price">view: ${item.views_count}</h4>
              </header>
              <p class="item-text">${item.body}
              </p>
              <h4 class="price">by ${item.user}</h4>
            </div>
          </article>
        </a>`
    });

      displayMenu = displayMenu.join("");
      sectionCenter.innerHTML = displayMenu;
    }


    function displayMenuButtion() {
      const categories = menu.reduce((value, item) => {
        if (!value.includes(item.category)) {
          value.push(item.category);
        }
        return value;
      }, ['all']
      );
      const categoryBtns = categories.map((category) => {
        return `<button class="filter-btn" data-id="${category}">${category}</button>`;
      })
        .join("");
      container.innerHTML = categoryBtns;
      // console.log(categoryBtns);
      const filterBtn = container.querySelectorAll(".filter-btn");
      filterBtn.forEach((btn) => {
        btn.addEventListener("click", (e) => {
          const category = e.currentTarget.dataset.id;
          const menuCategory = menu.filter((menuItem) => {
            if (menuItem.category === category) {
              return menuItem
            }
          });
          if (category === "all") {
            return displayMenuItem(menu);
          }
          else {
            return displayMenuItem(menuCategory)
          }
        });
      });
    }
</script>
{% endblock javascript %}

backend/templates/profile.html
{% extends "theme/base.html" %} 
{% load static %}
{% block title %}
<title>{{ block.super }} | {{ user.username }}</title>
{% endblock title %} {% block style %}
<style>
    body {
        background-color: #f9f9fa
    }
    
    .padding {
        padding: 3rem !important
    }
    
    .user-card-full {
        overflow: hidden
    }
    
    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
        border: none;
        margin-bottom: 30px
    }
    
    .m-r-0 {
        margin-right: 0px
    }
    
    .m-l-0 {
        margin-left: 0px
    }
    
    .user-card-full .user-profile {
        border-radius: 5px 0 0 5px
    }
    
    .bg-c-lite-green {
        background: -webkit-gradient(linear, left top, right top, from(#f29263), to(#ee5a6f));
        background: linear-gradient(to right, #ee5a6f, #f29263)
    }
    
    .user-profile {
        padding: 20px 0
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .m-b-25 {
        margin-bottom: 25px
    }
    
    .img-radius {
        border-radius: 5px
    }
    
    h6 {
        font-size: 14px
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    @media only screen and (min-width: 1400px) {
        p {
            font-size: 14px
        }
    }
    
    .card-block {
        padding: 1.25rem
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .card .card-block p {
        line-height: 25px
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .text-muted {
        color: #919aa3 !important
    }
    
    .b-b-default {
        border-bottom: 1px solid #e0e0e0
    }
    
    .f-w-600 {
        font-weight: 600
    }
    
    .m-b-20 {
        margin-bottom: 20px
    }
    
    .m-t-40 {
        margin-top: 20px
    }
    
    .p-b-5 {
        padding-bottom: 5px !important
    }
    
    .m-b-10 {
        margin-bottom: 10px
    }
    
    .m-t-40 {
        margin-top: 20px
    }
    
    .user-card-full .social-link li {
        display: inline-block
    }
    
    .user-card-full .social-link li a {
        font-size: 20px;
        margin: 0 10px 0 0;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out
    }
</style>
{% endblock style %} {% block body %}`
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25"> <img src="{{user.profile.image.url}}" width="100" class="img-radius" alt="User-Profile-Image"> </div>
                                <h6 class="f-w-600" style="text-transform: capitalize;">{{user.first_name}} {{user.last_name}}</h6>
                                <p><b>Bloger</b></p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                {% if request.user.is_authenticated and request.user == user %}
                                <a href="">
                                    <button type="button" class="btn btn-primary">
                                        Edit Profile <i class="fas fa-user-edit"></i>
                                    </button>
                                </a>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">{{user.email}}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Phone</p>
                                        <h6 class="text-muted f-w-400">{{user.profile.phone}}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Username</p>
                                        <h6 class="text-muted f-w-400">{{user.username}}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">DOB</p>
                                        <h6 class="text-muted f-w-400">{{user.profile.date_of_birth}}</h6>
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600"></h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600"></p>
                                        <h6 class="text-muted f-w-400"></h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600"></p>
                                        <h6 class="text-muted f-w-400"></h6>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %} 

{% block js %}
<script type="text/javascript">


</script>
{% endblock js %}